<?php
use UKMNorge\OAuth2\HandleAPICall;
use UKMNorge\Arrangement\Arrangement;


require_once('UKMconfig.inc.php');

// Hent videos fra CloudFlare Stream

$handleCall = new HandleAPICall(['id', 'erReportasje'], [], ['GET', 'POST'], false);

$arrangement = new Arrangement(get_option('pl_id'));

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$id = $handleCall->getArgument('id');
$erReportasje = $handleCall->getArgument('erReportasje');

// Hvis det er reportasje, så er det ikke koblet til et innslag ellers bruk innslag id
$creatorId = $erReportasje == 'true' ? '-p-' : '-b-';
$arrangementId = $arrangement->getId();

$url = ('https://api.cloudflare.com/client/v4/accounts/'. UKM_CLOUDFLARE_ACCOUNT_ID .'/stream?after=2014-01-02T02:20:00Z&before=2099-01-02T02:20:00Z&include_counts=false&creator=' . $arrangementId . $creatorId . $id);


// Sender Cloudflare account id and creator. Creator contains arrangement id (pl_id) og innslag som er identifisert med '-p-XXXX' eller arrangement id '-b-XXXX'
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Authorization: Bearer ' . UKM_CLOUDFLARE_VIDEO_KEY;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$handleCall->sendToClient(json_decode($result));