<?php
use UKMNorge\OAuth2\HandleAPICall;

require_once('UKMconfig.inc.php');

// Hent videos fra CloudFlare Stream
// Basert på WP bruker id

$handleCall = new HandleAPICall(['id', 'erReportasje'], [], ['GET', 'POST'], false);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$id = $handleCall->getArgument('id');
$erReportasje = $handleCall->getArgument('erReportasje');

// Hvis det er reportasje, så er det ikke koblet til et innslag ellers bruk innslag id
$creatorId = $erReportasje ? '-p-' : '-b-';

$wp_user_id = get_current_user_id();

$url = ('https://api.cloudflare.com/client/v4/accounts/'. UKM_CLOUDFLARE_ACCOUNT_ID .'/stream?after=2014-01-02T02:20:00Z&before=2025-01-02T02:20:00Z&include_counts=false&creator=' . $wp_user_id . $creatorId . $id);

// Sender Cloudflare account id and creator. Creator contains current wp user og innslag som er identifisert med '-p-XXXX' eller arrangement id '-b-XXXX'
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Authorization: Bearer ' . UKM_CLOUDFLARE_VIDEO_KEY;
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$handleCall->sendToClient(json_decode($result));