<?php
use UKMNorge\OAuth2\HandleAPICall;

// Hent videos fra CloudFlare Stream
// Basert på WP bruker id

$handleCall = new HandleAPICall([], [], ['GET', 'POST'], false);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

$wp_user_id = get_current_user_id();

curl_setopt($ch, CURLOPT_URL, 'https://api.cloudflare.com/client/v4/accounts/3fec674cb83e55d312b093cfd0f53482/stream?after=2014-01-02T02:20:00Z&before=2025-01-02T02:20:00Z&include_counts=false&creator=' . $wp_user_id);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


$headers = array();
$headers[] = 'Authorization: Bearer Cvpr2t5jG6ky-Uy0kJUmZo7atstMBJKo-TCHIcAS';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);

$handleCall->sendToClient(json_decode($result));